post http://localhost:3500/POSTproduct
Content-Type: application/json

{
    "id":4,
    "name":"AC",
    "price": 1000
}
###

get http://localhost:3500/GETproducts
###

get http://localhost:3500/GETproduct/3
###

put http://localhost:3500/PUTproduct/4
Content-Type: application/json

{
    "id":4,
    "name":"AC",
    "price": 45000
}
###

delete http://localhost:3500/DELETEproduct/3
